#!/usr/bin/env python3
"""Gera os builders .mjs dos modulos 4-8 a partir do template do modulo 3.

So substitui: DECK_ID, OUT_DIR path, output filename e o SLIDES array.
Tudo mais (infra, layouts, chrome) é identico entre todos os modulos.
"""

from pathlib import Path
import re
import subprocess
import sys

ROOT_ENT = Path(r"C:\Users\boliveid\OneDrive - NTT DATA EMEAL\Área de Trabalho\EntendimentoIAEngDados\build")
TEMPLATE_PATH = ROOT_ENT / "deck_builder_upskilling_modulo3.mjs"

# Configuracao de cada modulo: numero, dir, kicker, titulo curto e SLIDES (como string JS).
# Each SLIDES is the literal JS array body (between [ and ]).

MODULES = {
    4: {
        "dir": "04-python-dados",
        "title": "Python para Dados",
        "moment": "Pipeline simples é a base do pipeline em produção.",
        "slides": '''[
  { layout: "cover", theme: "dark",
    kicker: "TRILHA DE ENGENHARIA DE DADOS",
    title: "Python para Dados",
    subtitle: "Módulo 4  •  Sessão ao Vivo  •  2 horas",
    moment: "Pipeline simples é a base do pipeline em produção.",
  },
  { layout: "cards", theme: "light",
    kicker: "AGENDA",
    title: "O que vamos fazer hoje",
    subtitle: "Apresentação dos pipelines do Ex 4.3 e a ponte para o Módulo 5.",
    cards: [
      ["Abertura — 10 min", "Dúvidas do conteúdo: read_sql, groupby + agg, reset_index."],
      ["Conceitual — 15 min", "Reconhecer que o Ex 4.3 já é um ETL. Vocabulário formal."],
      ["Exercício — 75 min", "Apresentação dos pipelines em duplas. Discussão de estrutura e robustez."],
    ],
  },
  { layout: "section", theme: "dark", variant: "bookmark",
    sectionNumber: "01",
    title: "Abertura e Dúvidas",
    subtitle: "Identificar o que ficou menos claro no conteúdo assíncrono antes de avançar.",
  },
  { layout: "cards", theme: "light",
    kicker: "DÚVIDAS COMUNS",
    title: "Pontos que costumam gerar dúvida no conteúdo",
    subtitle: "Use estas perguntas para abrir a discussão se o grupo estiver tímido.",
    cards: [
      ["pd.read_sql", "Quando preferir read_sql vs sqlite3 puro? Quando você quer DataFrame direto, read_sql. Quando precisa de controle fino do cursor, sqlite3."],
      ["groupby + agg", "Múltiplas funções no mesmo agg: agg(total=('valor','sum'), n=('id','count')). Cria colunas nomeadas."],
      ["reset_index", "Após groupby, o índice vira a chave de agrupamento. reset_index() torna o resultado uma tabela plana de novo."],
    ],
  },
  { layout: "section", theme: "dark", variant: "bookmark",
    sectionNumber: "02",
    title: "Conceitual",
    subtitle: "A estrutura do Ex 4.3 já é um ETL — vamos nomear o que vocês fizeram.",
  },
  { layout: "example", theme: "light",
    kicker: "RECONHECER O PADRÃO ETL",
    title: "Extrair → Transformar → Carregar",
    subtitle: "O pipeline.py de vocês já segue este padrão. O Módulo 5 nomeia formalmente.",
    leftLabel: "ESTRUTURA UNIVERSAL",
    leftText: "EXTRAIR  →  TRANSFORMAR  →  CARREGAR\\n  (banco)      (pandas)       (parquet)\\n\\n\\nExtrair\\n- conector muda, estrutura permanece\\n- banco, API, CSV, planilha\\n\\nTransformar\\n- regras de negócio vivem aqui\\n- receita_por_categoria, ...\\n\\nCarregar\\n- arquivo, DW, bucket, tabela\\n- persistir de forma confiável",
    rightLabel: "PERGUNTAS PROVOCATIVAS",
    rightText: "1. Se o banco fosse uma API REST,\\n   o que mudaria no código?\\n   → Apenas extrair_vendas.\\n   Resto: igual.\\n\\n2. Para rodar todo dia às 6h,\\n   o que precisaríamos?\\n   → Agendamento, monitoramento,\\n   tratamento de erros.\\n\\n   = Módulo 5.",
    panelH: 380,
  },
  { layout: "section", theme: "dark", variant: "bookmark",
    sectionNumber: "03",
    title: "Apresentações em Grupo",
    subtitle: "Cada dupla apresenta seu pipeline. Vamos comparar abordagens e discutir robustez.",
  },
  { layout: "flow", theme: "light",
    kicker: "DINÂMICA DAS APRESENTAÇÕES",
    title: "Cada dupla em ~7 minutos",
    subtitle: "Mostrar, discutir, comparar. Após cada apresentação, o condutor levanta um ponto.",
    steps: [
      ["Mostrar", "Como organizou as funções? Cada função faz uma coisa só?"],
      ["Rodar", "Mostrar a saída ao vivo. Confirmar que os parquets foram gerados."],
      ["Discutir", "Uma coisa que achou difícil ou faria diferente."],
      ["Comparar", "Como esta abordagem se diferencia das anteriores?"],
    ],
  },
  { layout: "cards", theme: "light",
    kicker: "PONTOS DE DISCUSSÃO",
    title: "O que levantar após cada apresentação",
    subtitle: "Foque em estrutura, robustez e nomes. Estes três pilares sustentam um pipeline em produção.",
    cards: [
      ["Estrutura", "Funções com responsabilidade única? Nomes comunicam intenção? E se precisar adicionar uma 3ª agregação?"],
      ["Robustez", "Quebra se o banco não existir? saida/ é criado automaticamente? Trata caminhos inexistentes?"],
      ["Manutenção", "Outro engenheiro entende o pipeline lendo só o main()? Os tipos (type hints) estão claros?"],
    ],
  },
  { layout: "cards", theme: "light",
    kicker: "PERGUNTA CENTRAL DO BLOCO",
    title: "O que acontece se valor_total vier com nulos?",
    subtitle: "Deixe o grupo discutir por 5 min antes de mostrar a resposta. É um caso real de inconsistência silenciosa.",
    cards: [
      ["pandas não quebra", "sum() ignora NaN por padrão. O pipeline roda \\"limpo\\" e ninguém percebe nada."],
      ["Inconsistência silenciosa", "qtd_vendas conta a linha, mas a soma ignora — o ticket médio fica errado e ninguém sabe."],
      ["Decisão consciente", "Descartar a linha? Preencher com 0? Depende do negócio. Documente a decisão no código."],
    ],
  },
  { layout: "section", theme: "dark", variant: "bookmark",
    sectionNumber: "04",
    title: "Fechamento",
    subtitle: "Síntese do módulo, conexão direta com o Módulo 5, próximos passos.",
  },
  { layout: "quad", theme: "light",
    kicker: "OBJETIVOS DO MÓDULO 4",
    title: "O que o aluno é capaz de fazer agora",
    subtitle: "Todos os objetivos foram trabalhados em conteúdo, exercícios e apresentações ao vivo.",
    quadCards: [
      ["Estruturas Python para dados", "Listas, dicionários, comprehensions — vocabulário básico do dia-a-dia."],
      ["Ler SQLite com Python", "sqlite3 puro e pd.read_sql — duas formas, quando usar cada uma."],
      ["Pandas essencial", "Filtros, merges, groupby+agg, tratamento de nulos, funções reutilizáveis."],
      ["Reconhecer o padrão ETL", "Extrair → Transformar → Carregar como mental model permanente."],
    ],
  },
  { layout: "cards", theme: "light",
    kicker: "PRÓXIMO MÓDULO",
    title: "Módulo 5 — Lógica de ETL/ELT",
    subtitle: "Vocês têm pipeline manual. O Módulo 5 transforma em pipeline de produção.",
    cards: [
      ["ETL vs ELT", "Quando transformar antes vs depois da carga. Decisão de arquitetura."],
      ["Idempotência", "Rodar 3 vezes produz o mesmo resultado. Garantia obrigatória em produção."],
      ["Logging e erros", "O que logar para diagnosticar uma falha às 3h da manhã. Tratamento explícito."],
    ],
  },
  { layout: "closing", theme: "dark",
    title: "NTT DATA UNIVERSITY",
    subtitle: "Trilha de Engenharia de Dados  •  Módulo 4: Python para Dados",
  },
]''',
    },
    5: {
        "dir": "05-logica-etl-elt",
        "title": "Lógica de ETL/ELT",
        "moment": "Pipeline que falha silenciosamente é o pior pipeline.",
        "slides": '''[
  { layout: "cover", theme: "dark",
    kicker: "TRILHA DE ENGENHARIA DE DADOS",
    title: "Lógica de ETL/ELT",
    subtitle: "Módulo 5  •  Sessão ao Vivo  •  2 horas",
    moment: "Pipeline que falha silenciosamente é o pior pipeline.",
  },
  { layout: "cards", theme: "light",
    kicker: "AGENDA",
    title: "Da teoria ao pipeline robusto",
    subtitle: "Construir ao vivo o Ex 5.4 simulando uma falha para sentir a diferença que logging faz.",
    cards: [
      ["Abertura — 10 min", "Pergunta-chave: pipeline que quebra às 3h. O que precisa estar no código?"],
      ["Vocabulário — 15 min", "ETL vs ELT, extração incremental, idempotência, logging útil."],
      ["Exercício — 70 min", "Construir Ex 5.4 progressivamente. Simular falha e ver a diferença."],
    ],
  },
  { layout: "section", theme: "dark", variant: "bookmark",
    sectionNumber: "01",
    title: "Abertura",
    subtitle: "Pipeline quebra às 3h. Alguém precisa reprocessar tudo. O que precisa estar pronto?",
  },
  { layout: "cards", theme: "light",
    kicker: "AGENDA DETALHADA",
    title: "Cinco perguntas que guiam o módulo",
    subtitle: "Não há conceito abstrato hoje — formalizamos o que vocês já fizeram no Módulo 4.",
    cards: [
      ["1. Vocabulário", "ETL vs ELT (rápido — vocês já fizeram isso).  Extração incremental vs full load."],
      ["2. Idempotência", "O que é e por que salva vidas. Rodar 3 vezes = mesmo resultado."],
      ["3. Logging", "O que ajuda vs o que atrapalha. Pipeline que falha em silêncio é pior que pipeline que quebra."],
    ],
  },
  { layout: "section", theme: "dark", variant: "bookmark",
    sectionNumber: "02",
    title: "Vocês já fizeram ETL",
    subtitle: "Vamos nomear as decisões que vocês tomaram — e as que ainda não sabiam que precisavam tomar.",
  },
  { layout: "quad", theme: "light",
    kicker: "TRÊS PERGUNTAS PARA REFLEXÃO",
    title: "Provocações antes do exercício",
    subtitle: "Deixe o grupo responder. Conecte com as seções do conteúdo após cada uma.",
    quadCards: [
      ["Extração", "Se rodar amanhã, pega dados novos ou reprocessa tudo? Como sabe o que já processou?"],
      ["Carga", "Se rodar duas vezes seguidas, o arquivo terá o dobro de linhas ou as mesmas linhas?"],
      ["Erros", "Se o banco estiver fora, sabe o que aconteceu? Como você descobriria?"],
      ["ELT na nuvem", "Tudo aqui é ETL puro (Python+SQLite). Os princípios se aplicam direto a BigQuery/Snowflake."],
    ],
  },
  { layout: "section", theme: "dark", variant: "bookmark",
    sectionNumber: "03",
    title: "Construir o Ex 5.4 ao Vivo",
    subtitle: "Pipeline básico → adicionar logging → simular falha. Em grupos de 3-4 pessoas.",
  },
  { layout: "flow", theme: "light",
    kicker: "ESTRUTURA DO EXERCÍCIO",
    title: "Três partes progressivas em grupos",
    subtitle: "Cada parte tem ponto de parada para discussão coletiva antes da próxima.",
    steps: [
      ["3A — Básico (20 min)", "Ex 5.3 sem logging. Foco na estrutura ETL e cálculo de valor_unitario."],
      ["3B — Logging (20 min)", "Cada etapa loga início, fim, volume. Saída no terminal + arquivo."],
      ["3C — Falha (30 min)", "Alterar CAMINHO_DB para path inválido. Comparar com e sem try/except."],
    ],
  },
  { layout: "example", theme: "light",
    kicker: "ANTI-PADRÃO PERIGOSO",
    title: "Falha silenciosa é pior que falha com erro",
    subtitle: "Discuta este código antes de seguir. Onde você já viu algo parecido em produção?",
    leftLabel: "❌ ANTI-PADRÃO",
    leftText: "# NUNCA faça isso\\ntry:\\n    df = extrair(caminho_db)\\nexcept:\\n    pass  # silencia o erro\\n# ninguém sabe que falhou\\n# arquivo de saida pode estar\\n# vazio ou desatualizado\\n# alguém só descobre quando\\n# o cliente reclama",
    rightLabel: "✅ PADRÃO CORRETO",
    rightText: "try:\\n    df = extrair(caminho_db)\\nexcept FileNotFoundError as e:\\n    logger.error(\\n        f\\"Banco inacessível: {e}\\"\\n    )\\n    raise  # propaga o erro\\n\\n# alerta toca, time recebe,\\n# investigação começa imediatamente",
    panelH: 360,
  },
  { layout: "cards", theme: "light",
    kicker: "EXERCÍCIO FINAL DO BLOCO",
    title: "Alerta de qualidade — Ex 5.4 final",
    subtitle: "Mostrar como simular: alterar a query para retornar apenas metade dos dados.",
    cards: [
      ["O alerta", "Se > 5% das linhas forem descartadas na validação, logger.warning. Algo está errado na fonte."],
      ["Como testar", "Alterar temporariamente a query de extração para retornar metade dos dados."],
      ["Por que importa", "Detecta degradação silenciosa da qualidade da fonte antes que vire incidente."],
    ],
  },
  { layout: "section", theme: "dark", variant: "bookmark",
    sectionNumber: "04",
    title: "Prove a Idempotência",
    subtitle: "Critério de aceite de produção: provar que rodar 3 vezes produz o mesmo resultado.",
  },
  { layout: "example", theme: "light",
    kicker: "DEMONSTRAÇÃO AO VIVO",
    title: "Execute 3 vezes seguidas — verifique invariância",
    subtitle: "Mostre o número de linhas no resumo e o tamanho do arquivo após cada execução.",
    leftLabel: "COMANDOS",
    leftText: "$ python exercicios/etl_idempotente.py\\n$ python exercicios/etl_idempotente.py\\n$ python exercicios/etl_idempotente.py\\n\\n# Verificar\\nimport pandas as pd\\ndf = pd.read_parquet(\\n    'saida/vendas_processadas.parquet'\\n)\\nprint(f'Linhas: {len(df)}')\\n# Deve ser sempre o mesmo número",
    rightLabel: "DEBATE FINAL",
    rightText: "1. Se o destino fosse SQLite,\\n   como garantir idempotência?\\n   → upsert com INSERT OR REPLACE\\n\\n2. Para converter em ELT,\\n   o que mudaria?\\n   → Extração mais simples,\\n   transformação em SQL/dbt.\\n\\n3. Que mais loggar?\\n   → Usuário, versão do código,\\n   hash do arquivo, tempo por etapa.",
    panelH: 360,
  },
  { layout: "quad", theme: "light",
    kicker: "OBJETIVOS DO MÓDULO 5",
    title: "O que cobrimos hoje",
    subtitle: "Os princípios de pipeline de produção — independente de ferramenta ou cloud.",
    quadCards: [
      ["ETL vs ELT", "Decisão de onde transformar. Princípios iguais — implementação diferente."],
      ["Extração incremental", "Coluna de controle, ponto de checkpoint, reprocessamento seguro."],
      ["Idempotência + Carga", "Append vs replace vs upsert. Provar com 3 execuções consecutivas."],
      ["Logging + Tratamento", "O que loggar para investigar às 3h. raise > pass silencioso."],
    ],
  },
  { layout: "cards", theme: "light",
    kicker: "PRÓXIMO MÓDULO",
    title: "Módulo 6 — Engenharia de Pipelines",
    subtitle: "Hoje o pipeline roda manualmente. No Módulo 6 ele roda sozinho.",
    cards: [
      ["Orquestração", "Agendamento, dependências, retries. Airflow como referência de aprendizado."],
      ["DAGs", "Modelar dependências entre tarefas. Paralelo vs sequencial. Fan-out/fan-in."],
      ["Git para pipelines", "Branch, commit, PR. O mesmo rigor de uma API aplicado ao seu DAG."],
    ],
  },
  { layout: "closing", theme: "dark",
    title: "NTT DATA UNIVERSITY",
    subtitle: "Trilha de Engenharia de Dados  •  Módulo 5: Lógica de ETL/ELT",
  },
]''',
    },
    6: {
        "dir": "06-engenharia-pipelines",
        "title": "Engenharia de Pipelines",
        "moment": "Pipeline que precisa de alguém apertando botão não é produção.",
        "slides": '''[
  { layout: "cover", theme: "dark",
    kicker: "TRILHA DE ENGENHARIA DE DADOS",
    title: "Engenharia de Pipelines",
    subtitle: "Módulo 6  •  Sessão ao Vivo  •  2 horas",
    moment: "Pipeline que precisa de alguém apertando botão não é produção.",
  },
  { layout: "cards", theme: "light",
    kicker: "AGENDA",
    title: "Hoje vocês colocam o pipeline para rodar sozinho",
    subtitle: "Demo do Airflow + construção ao vivo de um DAG + Git para código de pipeline.",
    cards: [
      ["Demo Airflow — 15 min", "Materializar visualmente DAG, tarefa, run, retries antes de codar."],
      ["DAG ao vivo — 75 min", "Ex 6.1 + Ex 6.2 + Ex 6.3 (Git): desenhar, implementar, versionar."],
      ["Fechamento — 20 min", "Por que código de pipeline deve viver no repositório. Preview Módulo 7."],
    ],
  },
  { layout: "section", theme: "dark", variant: "bookmark",
    sectionNumber: "01",
    title: "Demo: Interface do Airflow",
    subtitle: "Materializar visualmente os conceitos antes de escrever o primeiro código.",
  },
  { layout: "cards", theme: "light",
    kicker: "O QUE MOSTRAR NA INTERFACE",
    title: "Cinco elementos da UI do Airflow",
    subtitle: "Compartilhe a tela e percorra cada um. Conecte sempre com a estrutura do DAG.",
    cards: [
      ["Lista de DAGs", "Cada linha é um pipeline. Schedule (0 7 * * *) e status da última run visíveis."],
      ["Graph View", "Tarefas como nós, dependências como setas. Paralelismo visível no mesmo nível."],
      ["Logs e falhas", "Click na tarefa → log. Stack trace de falhas + retries automáticos configurados."],
    ],
  },
  { layout: "section", theme: "dark", variant: "bookmark",
    sectionNumber: "02",
    title: "Construir o DAG ao Vivo",
    subtitle: "Ex 6.1: desenhar no papel. Ex 6.2: implementar em Airflow. Ex 6.3: versionar com Git.",
  },
  { layout: "flow", theme: "light",
    kicker: "FASES DO EXERCÍCIO",
    title: "Três fases — do papel ao Git",
    subtitle: "Cada fase tem ponto de parada para comparar abordagens entre participantes.",
    steps: [
      ["Desenhar — 10 min", "Cada um desenha o DAG no papel seguindo as regras de dependência."],
      ["Implementar — 45 min", "Construir dag_vendas.py ao vivo com a turma sugerindo cada decisão."],
      ["Versionar — 20 min", "Comandos Git ao vivo: branch, diff, commit, log. Turma acompanha no próprio terminal."],
    ],
  },
  { layout: "example", theme: "light",
    kicker: "EX 6.1 — GABARITO",
    title: "DAG do pipeline de vendas",
    subtitle: "Mostre o diagrama após os participantes desenharem. Explique paralelismo e fan-in.",
    leftLabel: "DIAGRAMA DO DAG",
    leftText: "extrair_vendas ────┐\\n                   │\\nextrair_clientes ──┼─► transformar\\n                   │       │\\nextrair_produtos ──┘       ▼\\n                       validar\\n                           │\\n                           ▼\\n                       carregar",
    rightLabel: "PRINCÍPIOS",
    rightText: "Paralelismo\\nAs 3 extrações rodam em paralelo\\n— são independentes entre si.\\n\\nFan-in\\ntransformar depende das 3.\\nSó começa quando todas terminam.\\n\\nSequencial\\nvalidar → carregar.\\nSó faz sentido em série.",
    panelH: 360,
  },
  { layout: "cards", theme: "light",
    kicker: "PERGUNTAS PARA GUIAR A IMPLEMENTAÇÃO",
    title: "Perguntas — uma para cada decisão do DAG",
    subtitle: "Faça uma de cada vez. Espere a turma responder antes de digitar.",
    cards: [
      ["Configuração", "Qual o dag_id? Expressão cron para 7h? Quantas retentativas? Intervalo entre elas?"],
      ["Dependências", "Como escrever a dependência fan-in das 3 extrações? [t1, t2, t3] >> transformar."],
      ["XCom", "Como passar dados entre tarefas? xcom_push e xcom_pull. Mostrar a aba XCom na UI."],
    ],
  },
  { layout: "example", theme: "light",
    kicker: "EX 6.3 — GIT NA PRÁTICA",
    title: "Sequência de comandos ao vivo",
    subtitle: "Execute cada um explicando o que está acontecendo. Turma acompanha no próprio terminal.",
    leftLabel: "COMANDOS",
    leftText: "$ git status\\n$ git checkout -b feat/adicionar-validacao\\n\\n# (editar o arquivo dag_vendas.py)\\n\\n$ git diff dag_vendas.py\\n$ git add dag_vendas.py\\n$ git commit -m \\"feat: valida registros\\"\\n$ git log --oneline",
    rightLabel: "PONTOS DE ENSINO",
    rightText: "1. git diff antes do add\\n   → revisar antes de commitar\\n\\n2. Mensagem descritiva no commit\\n   → feat: / fix: / refactor:\\n\\n3. git log --oneline\\n   → histórico legível\\n\\n4. Esqueceu o git add antes do commit?\\n   → mostrar o erro e corrigir",
    panelH: 340,
  },
  { layout: "section", theme: "dark", variant: "bookmark",
    sectionNumber: "03",
    title: "Fechamento",
    subtitle: "Por que pipeline em produção exige Git. Recap e preview do Módulo 7.",
  },
  { layout: "cards", theme: "light",
    kicker: "DISCUSSÃO COM A TURMA",
    title: "Código de pipeline é código de produção",
    subtitle: "Aplique o mesmo rigor que aplicaria a uma API. Branch, commit, PR, revisão — sempre.",
    cards: [
      ["Se o servidor cair", "Sem repositório, perdemos o pipeline. Ninguém sabe o que ele fazia. Sem histórico."],
      ["Anomalia nos dados", "Qual versão do pipeline rodou? Sem Git, impossível comparar com a versão anterior."],
      ["Onboarding", "Engenheiro novo abre o repo, lê o histórico, entende a evolução. Sem Git, depende de quem lembra."],
    ],
  },
  { layout: "quad", theme: "light",
    kicker: "OBJETIVOS DO MÓDULO 6",
    title: "O que cobrimos hoje",
    subtitle: "Três pilares: orquestração automatiza, DAGs modelam dependências, Git protege a produção.",
    quadCards: [
      ["O que é orquestração", "Agendamento + ordem + reprocessamento + notificação. Maestro do pipeline."],
      ["DAG, tarefas, runs", "Grafo direcionado acíclico. Cada execução é uma run. Operadores por tipo de tarefa."],
      ["Retries e alertas", "default_args com retries + retry_delay. Alertas por falha. on_failure_callback."],
      ["Git para pipelines", "Branch por feature, commits descritivos, PR para revisão. Pipeline = código de produção."],
    ],
  },
  { layout: "cards", theme: "light",
    kicker: "PRÓXIMO MÓDULO",
    title: "Módulo 7 — Armazenamento e Processamento",
    subtitle: "O pipeline roda. Onde os dados ficam? E quando o volume cresce além de uma máquina?",
    cards: [
      ["DW vs Data Lake vs Lakehouse", "Três arquiteturas, três casos de uso. Quando escolher cada uma."],
      ["Zonas do Data Lake", "Raw, trusted, refined. Como organizar os dados que seu pipeline produz."],
      ["Processamento distribuído", "PySpark conceitualmente. O que muda quando são 10 bilhões de linhas?"],
    ],
  },
  { layout: "closing", theme: "dark",
    title: "NTT DATA UNIVERSITY",
    subtitle: "Trilha de Engenharia de Dados  •  Módulo 6: Engenharia de Pipelines",
  },
]''',
    },
    7: {
        "dir": "07-armazenamento-processamento",
        "title": "Armazenamento e Processamento",
        "moment": "Código funciona com 3.000 linhas. E com 3 bilhões?",
        "slides": '''[
  { layout: "cover", theme: "dark",
    kicker: "TRILHA DE ENGENHARIA DE DADOS",
    title: "Armazenamento e Processamento",
    subtitle: "Módulo 7  •  Sessão ao Vivo  •  2 horas",
    moment: "Código funciona com 3.000 linhas. E com 3 bilhões?",
  },
  { layout: "cards", theme: "light",
    kicker: "AGENDA",
    title: "Onde os dados vivem — e o que muda quando crescem",
    subtitle: "Diagrama no whiteboard + Ex 7.2 (Data Lake) + Ex 7.4 (leitura PySpark) + escala.",
    cards: [
      ["Whiteboard — 20 min", "Diagrama DW vs Data Lake vs Lakehouse construído com a turma."],
      ["Exercício — 70 min", "Ex 7.2: zonas do Data Lake. Ex 7.4: ler e traduzir PySpark para pandas."],
      ["Escala — 20 min", "E se tivéssemos 10 bilhões de linhas? O que muda na arquitetura?"],
    ],
  },
  { layout: "section", theme: "dark", variant: "bookmark",
    sectionNumber: "01",
    title: "Três Arquiteturas",
    subtitle: "DW, Data Lake, Lakehouse — construir o diagrama com a turma, não mostrar pronto.",
  },
  { layout: "quad", theme: "light",
    kicker: "QUANDO USAR CADA UMA",
    title: "Conectando ao pipeline que vocês construíram",
    subtitle: "O dados.db é fonte transacional. Não é DW nem Lake — é de onde os dados saem.",
    quadCards: [
      ["Data Warehouse", "schema-on-write, dados limpos, SQL analítico. Snowflake/BQ/Redshift. SLA de BI."],
      ["Data Lake", "schema-on-read, dados brutos, formato livre. S3/ADLS/GCS. Volume e custo baixo."],
      ["Lakehouse", "Delta/Iceberg sobre Data Lake. ACID + time travel + barato. Convergência das duas."],
      ["Quando escolher", "DW: relatório com SLA. Lake: tudo bruto. Lakehouse: barato + garantias do DW."],
    ],
  },
  { layout: "cards", theme: "light",
    kicker: "PERGUNTAS DE ENGAJAMENTO",
    title: "Conecte cada conceito com a operação do dia-a-dia",
    subtitle: "Faça uma pergunta de cada vez. Deixe a turma responder antes de completar.",
    cards: [
      ["Pipeline falhou", "Em qual zona você olharia primeiro para investigar? → raw/, que guarda o original."],
      ["Dashboard com SLA 2s", "De onde ler? → DW ou refined/ bem particionado. raw/ não cabe."],
      ["Lei dos 7 anos", "Qual zona garante imutabilidade? → raw/. Por isso ela nunca é modificada."],
    ],
  },
  { layout: "section", theme: "dark", variant: "bookmark",
    sectionNumber: "02",
    title: "Exercício em Grupo",
    subtitle: "Ex 7.2 (zonas do Data Lake) e Ex 7.4 (PySpark → pandas) — colaborativo.",
  },
  { layout: "flow", theme: "light",
    kicker: "EX 7.2 — ZONAS DO DATA LAKE",
    title: "Cada um propõe, depois discutimos coletivamente",
    subtitle: "Sem ver gabarito. O ponto é o critério de decisão, não a resposta exata.",
    steps: [
      ["Individual — 10 min", "Desenhar a árvore de diretórios raw/trusted/refined com nomes realistas."],
      ["Discussão — 20 min", "2-3 voluntários compartilham. Discutir divergências."],
      ["Gabarito — 5 min", "Mostrar o gabarito e contrastar. Explicar o que justifica promoção raw → trusted."],
    ],
  },
  { layout: "cards", theme: "light",
    kicker: "PONTO DE ATENÇÃO",
    title: "Os dados \\"limpos\\" do banco não vão direto para trusted/",
    subtitle: "Discussão recorrente em equipes começando com Data Lake. Vale registrar o critério.",
    cards: [
      ["Limpos por quem?", "\\"Já estão limpos\\" significa o quê? Limpos pela origem ou validados pelo engenheiro?"],
      ["raw/ é sagrado", "raw/ é para o que veio da fonte sem você tocar. Auditoria, reprocessamento, rastreio."],
      ["trusted/ exige ação", "Promoção exige passagem por validações, padronização e checks documentados."],
    ],
  },
  { layout: "example", theme: "light",
    kicker: "EX 7.4 — PYSPARK → PANDAS",
    title: "Ler PySpark sem precisar instalar Spark",
    subtitle: "Desenvolver fluência. A lógica de negócio é a mesma — muda só o motor.",
    leftLabel: "PYSPARK (DISTRIBUÍDO)",
    leftText: "df.filter(F.col('valor_total') > 0)\\n  .groupBy('estado', 'categoria')\\n  .agg(\\n    F.sum('valor_total').alias('receita')\\n  )\\n  .withColumn('rank',\\n    F.row_number().over(\\n      Window.partitionBy('estado')\\n      .orderBy(F.desc('receita'))\\n    )\\n  )\\n  .filter(F.col('rank') <= 3)",
    rightLabel: "PANDAS (LOCAL)",
    rightText: "df = df[df['valor_total'] > 0]\\nagg = (df.groupby(['estado','categoria'])\\n         ['valor_total'].sum()\\n         .reset_index(name='receita'))\\nagg['rank'] = (\\n    agg.groupby('estado')['receita']\\n       .rank(method='first', ascending=False)\\n       .astype(int)\\n)\\ntop3 = agg[agg['rank'] <= 3]",
    panelH: 380,
  },
  { layout: "section", theme: "dark", variant: "bookmark",
    sectionNumber: "03",
    title: "E se fossem 10 bilhões?",
    subtitle: "Quatro perguntas em sequência. Deixe o grupo responder antes de complementar.",
  },
  { layout: "quad", theme: "light",
    kicker: "PERGUNTAS DE ESCALA",
    title: "O que muda quando o volume cresce 3 milhões de vezes",
    subtitle: "Lógica de negócio é a mesma. Infraestrutura de execução e armazenamento muda tudo.",
    quadCards: [
      ["pandas em 10B linhas?", "Trava — 6 colunas float = ~480 GB de RAM. Máquina comum tem 16-32 GB."],
      ["PySpark resolve?", "Sim, com cluster suficiente. Mesmo código, infraestrutura diferente."],
      ["Particionamento", "Top 3 de dez/2024 lê só ano=2024/mes=12/. Partition pruning é a salvação."],
      ["O que mais muda?", "Delta no lugar de Parquet. DW gerenciado para BI. Lógica permanece."],
    ],
  },
  { layout: "quad", theme: "light",
    kicker: "OBJETIVOS DO MÓDULO 7",
    title: "Recap dos 3 pontos do módulo",
    subtitle: "Não memorize ferramentas. Internalize o raciocínio sobre onde os dados vivem e por quê.",
    quadCards: [
      ["3 arquiteturas, 3 propósitos", "DW para BI com SLA. Lake para tudo bruto. Lakehouse converge os dois."],
      ["Zonas do Data Lake", "Raw, trusted, refined — não é burocracia, é o que torna pipeline auditável."],
      ["Processamento distribuído", "Existe porque dados crescem além de uma máquina. Spark abstrai a distribuição."],
      ["Particionamento", "Coluna escolhida muda o tempo de query de horas para segundos."],
    ],
  },
  { layout: "cards", theme: "light",
    kicker: "PRÓXIMO MÓDULO",
    title: "Módulo 8 — Qualidade e Observabilidade",
    subtitle: "Último módulo da trilha. Como garantir que o dado que entra no pipeline está correto.",
    cards: [
      ["5 dimensões de qualidade", "Completude, consistência, acurácia, timeliness, unicidade — vocabulário."],
      ["Validações no código", "Funções validar_* que falham rápido quando algo está fora do esperado."],
      ["TDD para pipelines", "pytest. Ciclo vermelho-verde. Testes que protegem contra regressões."],
    ],
  },
  { layout: "closing", theme: "dark",
    title: "NTT DATA UNIVERSITY",
    subtitle: "Trilha de Engenharia de Dados  •  Módulo 7: Armazenamento e Processamento",
  },
]''',
    },
    8: {
        "dir": "08-qualidade-observabilidade",
        "title": "Qualidade e Observabilidade",
        "moment": "Dado errado é pior que dado ausente.",
        "slides": '''[
  { layout: "cover", theme: "dark",
    kicker: "TRILHA DE ENGENHARIA DE DADOS",
    title: "Qualidade e Observabilidade",
    subtitle: "Módulo 8  •  Sessão ao Vivo  •  2 horas  •  Encerramento da Trilha",
    moment: "Dado errado é pior que dado ausente.",
  },
  { layout: "cards", theme: "light",
    kicker: "AGENDA",
    title: "Última sessão da trilha — qualidade, TDD e celebração",
    subtitle: "Análise coletiva de problemas + TDD na prática + linha do tempo dos 8 módulos.",
    cards: [
      ["Abertura — 10 min", "Alguém já encontrou dado errado em produção? Conectar com experiência real."],
      ["Análise — 30 min", "Ex 8.1: identificar problemas no dataset com as 5 dimensões."],
      ["TDD — 40 min", "Ex 8.3: ciclo vermelho-verde com pytest. Testes antes do código."],
      ["Trilha — 40 min", "Linha do tempo dos 8 módulos. O que fica. Próximos passos."],
    ],
  },
  { layout: "section", theme: "dark", variant: "bookmark",
    sectionNumber: "01",
    title: "Já encontrou dado errado em produção?",
    subtitle: "Abra com a pergunta direta. Histórias reais conectam com qualquer conceito do módulo.",
  },
  { layout: "cards", theme: "light",
    kicker: "O QUE COSTUMA APARECER",
    title: "Histórias frequentes — use como gancho",
    subtitle: "Não force se ninguém compartilhar. O Ex 8.1 vai gerar a conversa naturalmente.",
    cards: [
      ["Arquivo vazio sem alerta", "Pipeline rodou, salvou parquet com 0 linhas, ninguém percebeu por dias."],
      ["Duplicatas no dashboard", "Receita dobrou. Investigação encontra duplicata na fonte. Tudo retroativo é refeito."],
      ["Relatório com dados de ontem", "Pipeline atrasou. Relatório enviado para diretoria com snapshot do dia anterior."],
    ],
  },
  { layout: "section", theme: "dark", variant: "bookmark",
    sectionNumber: "02",
    title: "Análise Coletiva — Ex 8.1",
    subtitle: "Vocabulário das 5 dimensões aplicado a um dataset com 6 problemas reais.",
  },
  { layout: "quad", theme: "light",
    kicker: "AS 5 DIMENSÕES DE QUALIDADE",
    title: "Vocabulário comum para classificar problemas",
    subtitle: "Não são categorias mutuamente exclusivas. Um problema pode violar mais de uma.",
    quadCards: [
      ["Completude", "Há valores nulos onde não deveria? cliente_id None viola completude."],
      ["Consistência", "Integridade referencial. produto_id=999 referencia produto inexistente."],
      ["Acurácia + Validade", "Valores fazem sentido? quantidade=0 ou valor_total<0 violam regras de negócio."],
      ["Unicidade + Timeliness", "Duplicatas, datas inválidas (32-13-2024), dados antigos demais para o uso."],
    ],
  },
  { layout: "cards", theme: "light",
    kicker: "PONTO DE DISCUSSÃO RICO",
    title: "produto_id = 999 — qual dimensão viola?",
    subtitle: "Costuma gerar debate. Ambas as classificações estão corretas — o ponto é entender o porquê.",
    cards: [
      ["Acurácia", "999 não é um produto real. O valor está errado independente do que outras tabelas dizem."],
      ["Consistência", "999 não existe na tabela produtos. Viola a integridade referencial entre tabelas."],
      ["Dimensões não competem", "Destacam aspectos diferentes do mesmo problema. Escolha a que comunica melhor."],
    ],
  },
  { layout: "section", theme: "dark", variant: "bookmark",
    sectionNumber: "03",
    title: "TDD na Prática — Ex 8.3",
    subtitle: "Experimentar o ciclo vermelho-verde. Testes antes da implementação.",
  },
  { layout: "example", theme: "light",
    kicker: "FASE VERMELHA — 15 MIN",
    title: "Escrever os testes primeiro — todos falhando",
    subtitle: "Função transformar ainda vazia. Cada teste rodado retorna vermelho. Celebrar.",
    leftLabel: "PRIMEIRO TESTE",
    leftText: "import pandas as pd\\nimport pytest\\n\\ndef transformar(df):\\n    pass  # ainda não implementado\\n\\ndef make_df(**kwargs):\\n    defaults = {\\n        'venda_id': [1],\\n        'cliente_id': [10],\\n        'valor_total': [100.0],\\n        'quantidade': [2],\\n    }\\n    defaults.update(kwargs)\\n    return pd.DataFrame(defaults)\\n\\ndef test_caso_feliz():\\n    df = make_df()\\n    resultado = transformar(df)\\n    assert len(resultado) == 1",
    rightLabel: "EXECUÇÃO",
    rightText: "$ pytest test_pipeline.py -v\\n\\nFAILED test_caso_feliz\\n    AssertionError\\n\\n=========\\n1 failed in 0.02s\\n\\n\\nEste é o estado correto.\\n\\nO teste detecta o problema:\\na função ainda não existe.\\nAgora podemos implementar\\ncom confiança.",
    panelH: 380,
  },
  { layout: "example", theme: "light",
    kicker: "FASE VERDE — 20 MIN",
    title: "Implementar até que todos os testes passem",
    subtitle: "Sem escrever mais código do que o necessário. Cada teste guia uma decisão.",
    leftLabel: "IMPLEMENTAÇÃO",
    leftText: "def transformar(df):\\n    df = df.copy()\\n    df = df.drop_duplicates(\\n        subset=['venda_id'],\\n        keep='first'\\n    )\\n    df = df.dropna(\\n        subset=['cliente_id',\\n                'valor_total',\\n                'quantidade']\\n    )\\n    df = df[df['quantidade'] > 0]\\n    df['valor_unitario'] = (\\n        df['valor_total']\\n        / df['quantidade']\\n    )\\n    return df.reset_index(drop=True)",
    rightLabel: "EXECUÇÃO FINAL",
    rightText: "$ pytest test_pipeline.py -v\\n\\nPASSED test_caso_feliz\\nPASSED test_duplicatas\\nPASSED test_nulos\\nPASSED test_quantidade_zero\\n\\n=========\\n4 passed in 0.03s\\n\\n\\nO que mudou? Apenas o código.\\nOs testes são o contrato.\\nImplementação é como atendemos\\nao contrato.",
    panelH: 380,
  },
  { layout: "section", theme: "dark", variant: "bookmark",
    sectionNumber: "04",
    title: "Fechamento da Trilha",
    subtitle: "Linha do tempo dos 8 módulos. O que fica. Próximos passos com ferramentas específicas.",
  },
  { layout: "quad", theme: "light",
    kicker: "LINHA DO TEMPO — 1ª METADE",
    title: "Módulos 1 a 4 — fundação",
    subtitle: "Da pergunta \\"o que eu preciso do dado?\\" ao primeiro pipeline ETL em Python.",
    quadCards: [
      ["1 — SQL", "SELECT, JOIN, agregações. A pergunta \\"o que eu preciso do dado?\\""],
      ["2 — Modelagem", "Entidades, chaves, normalização. Como pensar relacionamentos entre dados."],
      ["3 — Formatos", "CSV, JSON, Parquet. Por que o formato importa para performance."],
      ["4 — Python", "pandas + sqlite3. Primeiro pipeline ETL funcionando."],
    ],
  },
  { layout: "quad", theme: "light",
    kicker: "LINHA DO TEMPO — 2ª METADE",
    title: "Módulos 5 a 8 — produção",
    subtitle: "Da idempotência aos testes de qualidade. Pipeline robusto e versionado.",
    quadCards: [
      ["5 — ETL/ELT", "Idempotência, logging, falha explícita. Pipeline que sobrevive."],
      ["6 — Pipelines", "Airflow, DAGs, Git. A diferença entre script e pipeline de produção."],
      ["7 — Armazenamento", "Data Lake, Lakehouse, Spark. Onde os dados vivem e como escalam."],
      ["8 — Qualidade", "5 dimensões, validações, TDD. Dado ruim é pior que dado ausente."],
    ],
  },
  { layout: "cards", theme: "light",
    kicker: "PRÓXIMOS PASSOS",
    title: "Ferramentas específicas que apoiam o que vocês aprenderam",
    subtitle: "A diferença entre usar e entender essas ferramentas é ter construído o fundamento na mão.",
    cards: [
      ["Qualidade declarativa", "Great Expectations + dbt tests. Validações estruturadas, relatórios automáticos."],
      ["Observabilidade em escala", "Monte Carlo + Soda. Detecção automática de anomalias. SLA de dados."],
      ["Orquestração em produção", "Airflow + Prefect em escala. Multi-tenancy, RBAC, observabilidade integrada."],
    ],
  },
  { layout: "closing", theme: "dark",
    title: "NTT DATA UNIVERSITY",
    subtitle: "Trilha de Engenharia de Dados  •  Módulo 8 — Encerramento  •  Parabéns pelo percurso",
  },
]''',
    },
}


def main():
    template = TEMPLATE_PATH.read_text(encoding="utf-8")
    print(f"Template lido: {TEMPLATE_PATH.name} ({len(template)} bytes)")

    # Pattern to find the SLIDES array in the template
    # It starts at "const SLIDES = [" and ends at the matching "];" at the start of a line
    slides_pattern = re.compile(
        r"const SLIDES = \[.*?\n\];",
        re.DOTALL,
    )

    for num, cfg in MODULES.items():
        print(f"\n=== Modulo {num} ===")
        content = template

        # 1) DECK_ID
        content = content.replace(
            'const DECK_ID = "upskilling-modulo3-v3";',
            f'const DECK_ID = "upskilling-modulo{num}-v3";',
        )

        # 2) OUT_DIR
        content = content.replace(
            'path.join(PROJECT_DIR, "modulos", "03-formatos-dados")',
            f'path.join(PROJECT_DIR, "modulos", "{cfg["dir"]}")',
        )

        # 3) Header comment
        content = content.replace(
            "// deck_builder_upskilling_modulo3.mjs — V3",
            f"// deck_builder_upskilling_modulo{num}.mjs — V3",
        )
        content = content.replace(
            "// Módulo 3 — Formatos de Dados",
            f"// Módulo {num} — {cfg['title']}",
        )

        # 4) Output filename
        content = content.replace(
            'path.join(OUT_DIR, "sessao-ao-vivo-modulo3-v3.pptx")',
            f'path.join(OUT_DIR, "sessao-ao-vivo-modulo{num}-v3.pptx")',
        )

        # 5) SLIDES array — usar lambda para evitar processamento de backslash
        # na string de replacement do re.sub (que interpretaria \n como
        # backreference invalido)
        new_slides_block = f"const SLIDES = {cfg['slides']};"
        content, count = slides_pattern.subn(lambda m: new_slides_block, content, count=1)
        if count != 1:
            raise RuntimeError(f"Modulo {num}: nao encontrou bloco SLIDES no template")

        # Save
        out_path = ROOT_ENT / f"deck_builder_upskilling_modulo{num}.mjs"
        out_path.write_text(content, encoding="utf-8")
        print(f"  Salvo: {out_path.name} ({len(content)} bytes)")


if __name__ == "__main__":
    main()
